### ISSUE TITLE
Overlap with vue-promised

### ISSUE THREAD

**Issue by posva** [byteboomers/vue-prom#3]
Hello, after taking a look at your lib, I wondered why did you create it even though I already created https://github.com/posva/vue-promised which also supports arrays and has a smaller size.
Is there anything there that is missing for you? I could help you to land a PR but it looks to me that you are more than qualified to do so 😄 

My goal here is to prevent ecosystem fraction, especially in such small utility libraries, so what do you say, do you want to join forces with vue-promised 🙂 ?

**Comment by botre** [comment]
Hello, thanks for reaching out!

First of all, I wasn't aware of vue-promised until a couple of days ago.
Secondly, I want to emphasize that I think vue-promised is a superb library, I especially like the fact that it supports arrays.

**Personal opinions justifying vue-promise's existence:**

- Familiar slot naming (pending/then/catch)

This immediately makes the library intuitive to  anyone who has ever worked with promises.
I appreciate your default slot logic and the fact that it makes everything a bit more concise but unfortunately it forces its users to learn and remember additional logic on top of the promise api they already know.

- Slot optionally with default values if no slot is provided

This is crucial in my opinion to reduce boilerplate related to the handling of both the pending and rejected states.

**Comment by posva** [comment]
Well, after seeing the tweets, I thought about adding optional slot names to match promises states (pending, resolved, rejected) 🙂 It's definitely something I'm not against and will probably add.

The optional default values for slots is also interesting, but rather than having _Loading_ or _Rejected_, I was more thinking about a config option that can be set to a component or some text (for convenience)

I'm pretty sure we can have only one package 😉

**Comment by botre** [comment]
I personally think that the promise states (fulfilled & rejected) are less known and harder to type compared to their handlers (then & catch). 

I'm planning to make the default rendered labels globally customizable (text or component).
 
While I fully agree that ecosystem fraction is not ideal, it is my opinion that it is probably too early to merge our approaches. _For now,_ I suggest we let both libraries grow organically, if our long-term directions still turn out to be similar in a couple of months, then I will gladly reconsider the matter.
